api_platform:
    defaults:
        pagination_client_items_per_page: true
        pagination_client_enabled: true
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage
            enabled_parameter_name: pagination