easy_admin:
    entities:
        Set:
            form:
                fields:
                    - 
                        property: translations
                        label: ''
                        type: 'A2lix\TranslationFormBundle\Form\Type\TranslationsType'
                        type_options: 
                            fields:
                                content: 
                                    field_type: 'EasyCorp\Bundle\EasyAdminBundle\Form\Type\TextEditorType'